[UPD] - Updated run_tests

diff --git a/bin/run_tests b/bin/run_tests
--- a/bin/run_tests
+++ b/bin/run_tests
@@ -15,39 +15,29 @@ if [ -z "$ADDONS" ]; then
     exit 0
 fi
 
-# Use test-tags=mytag1,mytag2 to run tests with specific tags. 
-# Ex./run_tests.sh --tags=mytag1,mytag2
-# Check if test tags are provided
-if [ $# -eq 0 ]; then
-    echo "No test tags provided. Exiting with error."
-    exit 1
+echo "Running tests with coverage..."
+unbuffer coverage run --source="${ADDONS_DIR}" --branch \
+    $(find /opt -name odoo-bin) \
+    -d ${PGDATABASE} \
+    -i ${ADDONS} \
+    --test-enable \
+    --stop-after-init \
+    --log-level=test \
+    --"$@"
+
+echo "Generating coverage report..."
+coverage report
+
+echo "Calculating coverage..."
+coverage_percentage=$(coverage report | grep TOTAL | awk '{print $6}')
+
+# Check if coverage is greater than 60%
+required_coverage=60.0
+
+if (( $(echo "$coverage_percentage >= $required_coverage" | bc -l) )); then
+    echo "Coverage (${coverage_percentage}%) is greater than or equal to ${required_coverage}% required."
+    exit 0
 else
-    echo "Test tags provided."
-    echo "Running tests with coverage..."
-    unbuffer coverage run --source="${ADDONS_DIR}" --branch \
-        $(find /opt -name odoo-bin) \
-        -d ${PGDATABASE} \
-        -i ${ADDONS} \
-        --test-enable \
-        --stop-after-init \
-        --log-level=test \
-        --"$@"
-
-    echo "Generating coverage report..."
-    coverage report
-
-    echo "Calculating coverage..."
-    coverage_percentage=$(coverage report | grep TOTAL | awk '{print $6}')
-
-    # Check if coverage is greater than 60%
-    required_coverage=60.0
-
-    if (( $(echo "$coverage_percentage >= $required_coverage" | bc -l) )); then
-        echo "Coverage (${coverage_percentage}%) is greater than or equal to ${required_coverage}% required."
-        exit 0
-    else
-        echo "Coverage (${coverage_percentage}%) is less than ${required_coverage}% required."
-        exit 1
-    fi
-
+    echo "Coverage (${coverage_percentage}%) is less than ${required_coverage}% required."
+    exit 1
 fi
